[2021-04-25 09:09:07,795] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: file_sensor_dag.external_sensor_task 2021-04-25T09:09:07.002593+00:00 [queued]>
[2021-04-25 09:09:07,822] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: file_sensor_dag.external_sensor_task 2021-04-25T09:09:07.002593+00:00 [queued]>
[2021-04-25 09:09:07,822] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 09:09:07,822] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2021-04-25 09:09:07,822] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 09:09:07,853] {taskinstance.py:1089} INFO - Executing <Task(ExternalTaskSensor): external_sensor_task> on 2021-04-25T09:09:07.002593+00:00
[2021-04-25 09:09:07,877] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_sensor_dag', 'external_sensor_task', '2021-04-25T09:09:07.002593+00:00', '--job-id', '803', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/sensor/simple_sensor_dag.py', '--cfg-path', '/tmp/tmp944grj6j', '--error-file', '/tmp/tmp4j8qfjvy']
[2021-04-25 09:09:07,882] {standard_task_runner.py:77} INFO - Job 803: Subtask external_sensor_task
[2021-04-25 09:09:07,863] {standard_task_runner.py:52} INFO - Started process 67 to run task
[2021-04-25 09:09:08,000] {logging_mixin.py:104} INFO - Running <TaskInstance: file_sensor_dag.external_sensor_task 2021-04-25T09:09:07.002593+00:00 [running]> on host d6e2455ef0ec
[2021-04-25 09:09:08,098] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_sensor_dag
AIRFLOW_CTX_TASK_ID=external_sensor_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T09:09:07.002593+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-25T09:09:07.002593+00:00
[2021-04-25 09:09:08,099] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:09:07.002593+00:00 ... 
[2021-04-25 09:10:08,134] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:09:07.002593+00:00 ... 
[2021-04-25 09:11:08,204] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:09:07.002593+00:00 ... 
[2021-04-25 09:12:08,264] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:09:07.002593+00:00 ... 
[2021-04-25 09:13:08,316] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:09:07.002593+00:00 ... 
[2021-04-25 09:13:35,831] {local_task_job.py:188} WARNING - State of this instance has been externally set to None. Terminating instance.
[2021-04-25 09:13:35,851] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 67
[2021-04-25 09:13:35,853] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-04-25 09:13:35,867] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 243, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-04-25 09:13:35,891] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=file_sensor_dag, task_id=external_sensor_task, execution_date=20210425T090907, start_date=20210425T090907, end_date=20210425T091335
[2021-04-25 09:13:35,948] {process_utils.py:66} INFO - Process psutil.Process(pid=67, status='terminated', exitcode=1, started='09:09:07') (67) terminated with exit code 1
