[2021-04-25 14:19:39,639] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: templated_bash_operator_dag.read_json_file_task 2021-04-25T14:14:34.617713+00:00 [queued]>
[2021-04-25 14:19:39,697] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: templated_bash_operator_dag.read_json_file_task 2021-04-25T14:14:34.617713+00:00 [queued]>
[2021-04-25 14:19:39,698] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 14:19:39,698] {taskinstance.py:1069} INFO - Starting attempt 2 of 3
[2021-04-25 14:19:39,698] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 14:19:39,738] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): read_json_file_task> on 2021-04-25T14:14:34.617713+00:00
[2021-04-25 14:19:39,755] {standard_task_runner.py:52} INFO - Started process 142 to run task
[2021-04-25 14:19:39,777] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'templated_bash_operator_dag', 'read_json_file_task', '2021-04-25T14:14:34.617713+00:00', '--job-id', '936', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator/templated_bash_operator_dag.py', '--cfg-path', '/tmp/tmpoouk105w', '--error-file', '/tmp/tmpgqlywdyx']
[2021-04-25 14:19:39,782] {standard_task_runner.py:77} INFO - Job 936: Subtask read_json_file_task
[2021-04-25 14:19:39,952] {logging_mixin.py:104} INFO - Running <TaskInstance: templated_bash_operator_dag.read_json_file_task 2021-04-25T14:14:34.617713+00:00 [running]> on host d6e2455ef0ec
[2021-04-25 14:19:40,101] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=templated_bash_operator_dag
AIRFLOW_CTX_TASK_ID=read_json_file_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T14:14:34.617713+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-25T14:14:34.617713+00:00
[2021-04-25 14:19:40,102] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-25 14:19:40,106] {bash.py:158} INFO - Running command: 
    execution date: 2021-04-25
    cat todo.json
    
[2021-04-25 14:19:40,140] {bash.py:169} INFO - Output:
[2021-04-25 14:19:40,143] {bash.py:173} INFO - bash: line 1: execution: command not found
[2021-04-25 14:19:40,146] {bash.py:173} INFO - cat: todo.json: No such file or directory
[2021-04-25 14:19:40,150] {bash.py:177} INFO - Command exited with return code 1
[2021-04-25 14:19:40,187] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-04-25 14:19:40,195] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=templated_bash_operator_dag, task_id=read_json_file_task, execution_date=20210425T141434, start_date=20210425T141939, end_date=20210425T141940
[2021-04-25 14:19:40,293] {local_task_job.py:146} INFO - Task exited with return code 1
