[2021-04-25 10:55:10,644] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: external_sensor_dag.external_sensor_task 2021-04-25T10:54:00+00:00 [queued]>
[2021-04-25 10:55:10,660] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: external_sensor_dag.external_sensor_task 2021-04-25T10:54:00+00:00 [queued]>
[2021-04-25 10:55:10,660] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 10:55:10,660] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2021-04-25 10:55:10,660] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 10:55:10,670] {taskinstance.py:1089} INFO - Executing <Task(ExternalTaskSensor): external_sensor_task> on 2021-04-25T10:54:00+00:00
[2021-04-25 10:55:10,674] {standard_task_runner.py:52} INFO - Started process 91 to run task
[2021-04-25 10:55:10,678] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'external_sensor_dag', 'external_sensor_task', '2021-04-25T10:54:00+00:00', '--job-id', '855', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/sensor/external_sensor.py', '--cfg-path', '/tmp/tmporn7q__g', '--error-file', '/tmp/tmpdy_ymdcf']
[2021-04-25 10:55:10,678] {standard_task_runner.py:77} INFO - Job 855: Subtask external_sensor_task
[2021-04-25 10:55:10,731] {logging_mixin.py:104} INFO - Running <TaskInstance: external_sensor_dag.external_sensor_task 2021-04-25T10:54:00+00:00 [running]> on host d6e2455ef0ec
[2021-04-25 10:55:10,780] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=external_sensor_dag
AIRFLOW_CTX_TASK_ID=external_sensor_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T10:54:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T10:54:00+00:00
[2021-04-25 10:55:10,780] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T10:54:00+00:00 ... 
[2021-04-25 10:55:15,749] {local_task_job.py:188} WARNING - State of this instance has been externally set to None. Terminating instance.
[2021-04-25 10:55:15,754] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 91
[2021-04-25 10:55:15,754] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-04-25 10:55:15,766] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 243, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-04-25 10:55:15,778] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=external_sensor_dag, task_id=external_sensor_task, execution_date=20210425T105400, start_date=20210425T105510, end_date=20210425T105515
[2021-04-25 10:55:15,847] {process_utils.py:66} INFO - Process psutil.Process(pid=91, status='terminated', exitcode=1, started='10:55:10') (91) terminated with exit code 1
