[2021-04-25 14:24:28,639] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: templated_bash_operator_dag.read_json_file_task 2021-04-25T14:19:24.955739+00:00 [queued]>
[2021-04-25 14:24:28,653] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: templated_bash_operator_dag.read_json_file_task 2021-04-25T14:19:24.955739+00:00 [queued]>
[2021-04-25 14:24:28,653] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 14:24:28,653] {taskinstance.py:1069} INFO - Starting attempt 2 of 3
[2021-04-25 14:24:28,653] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 14:24:28,671] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): read_json_file_task> on 2021-04-25T14:19:24.955739+00:00
[2021-04-25 14:24:28,675] {standard_task_runner.py:52} INFO - Started process 157 to run task
[2021-04-25 14:24:28,679] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'templated_bash_operator_dag', 'read_json_file_task', '2021-04-25T14:19:24.955739+00:00', '--job-id', '939', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/bash_operator/templated_bash_operator_dag.py', '--cfg-path', '/tmp/tmpsnn9b00d', '--error-file', '/tmp/tmp8x6fo5rp']
[2021-04-25 14:24:28,679] {standard_task_runner.py:77} INFO - Job 939: Subtask read_json_file_task
[2021-04-25 14:24:28,730] {logging_mixin.py:104} INFO - Running <TaskInstance: templated_bash_operator_dag.read_json_file_task 2021-04-25T14:19:24.955739+00:00 [running]> on host d6e2455ef0ec
[2021-04-25 14:24:28,777] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=templated_bash_operator_dag
AIRFLOW_CTX_TASK_ID=read_json_file_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T14:19:24.955739+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-25T14:19:24.955739+00:00
[2021-04-25 14:24:28,777] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-04-25 14:24:28,778] {bash.py:158} INFO - Running command: 
    "execution date: 2021-04-25"
    cat todo.json
    
[2021-04-25 14:24:28,790] {bash.py:169} INFO - Output:
[2021-04-25 14:24:28,792] {bash.py:173} INFO - bash: line 1: execution date: 2021-04-25: command not found
[2021-04-25 14:24:28,794] {bash.py:173} INFO - cat: todo.json: No such file or directory
[2021-04-25 14:24:28,795] {bash.py:177} INFO - Command exited with return code 1
[2021-04-25 14:24:28,806] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-04-25 14:24:28,809] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=templated_bash_operator_dag, task_id=read_json_file_task, execution_date=20210425T141924, start_date=20210425T142428, end_date=20210425T142428
[2021-04-25 14:24:28,853] {local_task_job.py:146} INFO - Task exited with return code 1
