[2021-04-25 08:07:32,651] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: send_email_dag.send_email_task 2021-04-25T08:07:30.305270+00:00 [queued]>
[2021-04-25 08:07:32,666] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: send_email_dag.send_email_task 2021-04-25T08:07:30.305270+00:00 [queued]>
[2021-04-25 08:07:32,666] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 08:07:32,666] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2021-04-25 08:07:32,666] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 08:07:32,675] {taskinstance.py:1089} INFO - Executing <Task(EmailOperator): send_email_task> on 2021-04-25T08:07:30.305270+00:00
[2021-04-25 08:07:32,679] {standard_task_runner.py:52} INFO - Started process 65 to run task
[2021-04-25 08:07:32,682] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'send_email_dag', 'send_email_task', '2021-04-25T08:07:30.305270+00:00', '--job-id', '792', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/email_operator/send_email.py', '--cfg-path', '/tmp/tmpr7lucst4', '--error-file', '/tmp/tmpzmucee4n']
[2021-04-25 08:07:32,683] {standard_task_runner.py:77} INFO - Job 792: Subtask send_email_task
[2021-04-25 08:07:32,730] {logging_mixin.py:104} INFO - Running <TaskInstance: send_email_dag.send_email_task 2021-04-25T08:07:30.305270+00:00 [running]> on host d6e2455ef0ec
[2021-04-25 08:07:32,780] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=send_email_dag
AIRFLOW_CTX_TASK_ID=send_email_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T08:07:30.305270+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-25T08:07:30.305270+00:00
[2021-04-25 08:07:32,785] {configuration.py:352} WARNING - section/key [smtp/smtp_user] not found in config
[2021-04-25 08:07:32,785] {email.py:184} INFO - Email alerting: attempt 1
[2021-04-25 08:07:32,788] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/email.py", line 87, in execute
    mime_charset=self.mime_charset,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/email.py", line 62, in send_email
    **kwargs,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/email.py", line 97, in send_email_smtp
    send_mime_email(e_from=smtp_mail_from, e_to=recipients, mime_msg=msg, dryrun=dryrun)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/email.py", line 186, in send_mime_email
    conn = _get_smtp_connection(smtp_host, smtp_port, smtp_timeout, smtp_ssl)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/email.py", line 220, in _get_smtp_connection
    else smtplib.SMTP(host=host, port=port, timeout=timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.6/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.6/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/local/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
[2021-04-25 08:07:32,792] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=send_email_dag, task_id=send_email_task, execution_date=20210425T080730, start_date=20210425T080732, end_date=20210425T080732
[2021-04-25 08:07:32,816] {local_task_job.py:146} INFO - Task exited with return code 1
