[2021-04-25 08:13:20,201] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: write_file_python_operator.fetch_and_write_a_file_task 2021-04-25T08:13:18.431306+00:00 [queued]>
[2021-04-25 08:13:20,231] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: write_file_python_operator.fetch_and_write_a_file_task 2021-04-25T08:13:18.431306+00:00 [queued]>
[2021-04-25 08:13:20,232] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 08:13:20,232] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2021-04-25 08:13:20,232] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 08:13:20,255] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): fetch_and_write_a_file_task> on 2021-04-25T08:13:18.431306+00:00
[2021-04-25 08:13:20,266] {standard_task_runner.py:52} INFO - Started process 49 to run task
[2021-04-25 08:13:20,272] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'write_file_python_operator', 'fetch_and_write_a_file_task', '2021-04-25T08:13:18.431306+00:00', '--job-id', '794', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/python_operator/write_file_python_operator.py', '--cfg-path', '/tmp/tmp_dzq981q', '--error-file', '/tmp/tmp_i_l4y47']
[2021-04-25 08:13:20,272] {standard_task_runner.py:77} INFO - Job 794: Subtask fetch_and_write_a_file_task
[2021-04-25 08:13:20,342] {logging_mixin.py:104} INFO - Running <TaskInstance: write_file_python_operator.fetch_and_write_a_file_task 2021-04-25T08:13:18.431306+00:00 [running]> on host d6e2455ef0ec
[2021-04-25 08:13:20,408] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=write_file_python_operator
AIRFLOW_CTX_TASK_ID=fetch_and_write_a_file_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T08:13:18.431306+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-25T08:13:18.431306+00:00
[2021-04-25 08:13:21,109] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/python_operator/write_file_python_operator.py", line 22, in fetch_and_write
    with open(os.path.join(os.path.dirname(__file__), path_to_write), 'wb') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/python_operator/../src/todo.json'
[2021-04-25 08:13:21,114] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=write_file_python_operator, task_id=fetch_and_write_a_file_task, execution_date=20210425T081318, start_date=20210425T081320, end_date=20210425T081321
[2021-04-25 08:13:21,171] {local_task_job.py:146} INFO - Task exited with return code 1
