[2021-04-25 09:53:47,525] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: file_sensor_dag.external_sensor_task 2021-04-25T09:53:45.316901+00:00 [queued]>
[2021-04-25 09:53:47,558] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: file_sensor_dag.external_sensor_task 2021-04-25T09:53:45.316901+00:00 [queued]>
[2021-04-25 09:53:47,558] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 09:53:47,559] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2021-04-25 09:53:47,559] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 09:53:47,599] {taskinstance.py:1089} INFO - Executing <Task(ExternalTaskSensor): external_sensor_task> on 2021-04-25T09:53:45.316901+00:00
[2021-04-25 09:53:47,622] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_sensor_dag', 'external_sensor_task', '2021-04-25T09:53:45.316901+00:00', '--job-id', '830', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/sensor/simple_sensor_dag.py', '--cfg-path', '/tmp/tmpv_wtzt80', '--error-file', '/tmp/tmp3viy0c23']
[2021-04-25 09:53:47,606] {standard_task_runner.py:52} INFO - Started process 69 to run task
[2021-04-25 09:53:47,623] {standard_task_runner.py:77} INFO - Job 830: Subtask external_sensor_task
[2021-04-25 09:53:47,756] {logging_mixin.py:104} INFO - Running <TaskInstance: file_sensor_dag.external_sensor_task 2021-04-25T09:53:45.316901+00:00 [running]> on host d6e2455ef0ec
[2021-04-25 09:53:47,900] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_sensor_dag
AIRFLOW_CTX_TASK_ID=external_sensor_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T09:53:45.316901+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-04-25T09:53:45.316901+00:00
[2021-04-25 09:53:47,902] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:53:45.316901+00:00 ... 
[2021-04-25 09:54:47,954] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:53:45.316901+00:00 ... 
[2021-04-25 09:55:48,024] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:53:45.316901+00:00 ... 
[2021-04-25 09:56:48,084] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:53:45.316901+00:00 ... 
[2021-04-25 09:57:48,151] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:53:45.316901+00:00 ... 
[2021-04-25 09:58:48,214] {external_task.py:154} INFO - Poking for write_file_python_operator.fetch_and_write_a_file_task on 2021-04-25T09:53:45.316901+00:00 ... 
[2021-04-25 09:59:00,746] {local_task_job.py:77} ERROR - Received SIGTERM. Terminating subprocesses
[2021-04-25 09:59:00,748] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 69
[2021-04-25 09:59:00,748] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-04-25 09:59:00,785] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 243, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-04-25 09:59:00,788] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=file_sensor_dag, task_id=external_sensor_task, execution_date=20210425T095345, start_date=20210425T095347, end_date=20210425T095900
[2021-04-25 09:59:00,907] {process_utils.py:66} INFO - Process psutil.Process(pid=69, status='terminated', exitcode=1, started='09:53:47') (69) terminated with exit code 1
