[2021-04-25 13:37:18,346] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: write_file_python_operator.write_execution_time_task 2021-04-25T13:34:00+00:00 [queued]>
[2021-04-25 13:37:18,360] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: write_file_python_operator.write_execution_time_task 2021-04-25T13:34:00+00:00 [queued]>
[2021-04-25 13:37:18,360] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 13:37:18,360] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2021-04-25 13:37:18,360] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 13:37:18,375] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): write_execution_time_task> on 2021-04-25T13:34:00+00:00
[2021-04-25 13:37:18,383] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'write_file_python_operator', 'write_execution_time_task', '2021-04-25T13:34:00+00:00', '--job-id', '898', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/python_operator/write_file_python_operator.py', '--cfg-path', '/tmp/tmpow_15fet', '--error-file', '/tmp/tmpni8gbiqi']
[2021-04-25 13:37:18,384] {standard_task_runner.py:77} INFO - Job 898: Subtask write_execution_time_task
[2021-04-25 13:37:18,379] {standard_task_runner.py:52} INFO - Started process 62 to run task
[2021-04-25 13:37:18,429] {logging_mixin.py:104} INFO - Running <TaskInstance: write_file_python_operator.write_execution_time_task 2021-04-25T13:34:00+00:00 [running]> on host d6e2455ef0ec
[2021-04-25 13:37:18,484] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=write_file_python_operator
AIRFLOW_CTX_TASK_ID=write_execution_time_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T13:34:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T13:34:00+00:00
[2021-04-25 13:37:18,487] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 117, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 128, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/python_operator/write_file_python_operator.py", line 20, in fetch_and_write
    response = requests.get(url)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/sessions.py", line 466, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/models.py", line 316, in prepare
    self.prepare_url(url, params)
  File "/home/airflow/.local/lib/python3.6/site-packages/requests/models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant http://?
[2021-04-25 13:37:18,494] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=write_file_python_operator, task_id=write_execution_time_task, execution_date=20210425T133400, start_date=20210425T133718, end_date=20210425T133718
[2021-04-25 13:37:18,519] {local_task_job.py:146} INFO - Task exited with return code 1
