[2021-04-25 11:35:56,507] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: file_sensor_dag.file_sensor_task 2021-04-25T11:34:00+00:00 [queued]>
[2021-04-25 11:35:56,522] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: file_sensor_dag.file_sensor_task 2021-04-25T11:34:00+00:00 [queued]>
[2021-04-25 11:35:56,522] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 11:35:56,522] {taskinstance.py:1069} INFO - Starting attempt 1 of 3
[2021-04-25 11:35:56,522] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-04-25 11:35:56,530] {taskinstance.py:1089} INFO - Executing <Task(FileSensor): file_sensor_task> on 2021-04-25T11:34:00+00:00
[2021-04-25 11:35:56,534] {standard_task_runner.py:52} INFO - Started process 123 to run task
[2021-04-25 11:35:56,539] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'file_sensor_dag', 'file_sensor_task', '2021-04-25T11:34:00+00:00', '--job-id', '871', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/sensor/file_sensor.py', '--cfg-path', '/tmp/tmp9lo26f1m', '--error-file', '/tmp/tmpdsdj72x_']
[2021-04-25 11:35:56,539] {standard_task_runner.py:77} INFO - Job 871: Subtask file_sensor_task
[2021-04-25 11:35:56,590] {logging_mixin.py:104} INFO - Running <TaskInstance: file_sensor_dag.file_sensor_task 2021-04-25T11:34:00+00:00 [running]> on host d6e2455ef0ec
[2021-04-25 11:35:56,642] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=file_sensor_dag
AIRFLOW_CTX_TASK_ID=file_sensor_task
AIRFLOW_CTX_EXECUTION_DATE=2021-04-25T11:34:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-04-25T11:34:00+00:00
[2021-04-25 11:35:56,655] {filesystem.py:56} INFO - Poking for file /opt/airflow/dags/python_operator/todo.json
[2021-04-25 11:38:43,199] {local_task_job.py:188} WARNING - State of this instance has been externally set to None. Terminating instance.
[2021-04-25 11:38:43,205] {process_utils.py:100} INFO - Sending Signals.SIGTERM to GPID 123
[2021-04-25 11:38:43,206] {taskinstance.py:1265} ERROR - Received SIGTERM. Terminating subprocesses.
[2021-04-25 11:38:43,215] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/sensors/base.py", line 243, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1267, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2021-04-25 11:38:43,219] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=file_sensor_dag, task_id=file_sensor_task, execution_date=20210425T113400, start_date=20210425T113556, end_date=20210425T113843
[2021-04-25 11:38:43,259] {process_utils.py:66} INFO - Process psutil.Process(pid=123, status='terminated', exitcode=1, started='11:35:56') (123) terminated with exit code 1
